### PR TITLE
test: add registry tests

### LINKED ISSUE #119: Adding some mocha here
Hi @guybedford

Like I was a bit lost and uncertain of what is actually registered here I wrote some tests (:

I made a little poke and find out that [19 over 155 packages are broken](https://travis-ci.org/douglasduteil/registry/builds/47653659)
( testing made by `curl` the GitHub API).

It would be cool to validate PR and auto check semver format for example (following #118)

What you think ?

### PR DESCRIPTION
**Pull request by douglasduteil**
Following https://github.com/jspm/jspm-cli/issues/145
Here comes the registry tests 
result here : https://travis-ci.org/douglasduteil/registry/builds/48898010
Closes #119

### CODE REVIEW

**Comment by djindjic** [comment]
like

**Comment by guybedford** [comment]
Thanks so much for looking into this - I'm really keen to expand automated coverage of real library install operations against the registry.

That said, this seems to just be checking that the repos exist? How does it handle redirects? I'm not sure what value it's providing?

**Comment by douglasduteil** [comment]
> That said, this seems to just be checking that the repos exist?

Yes

> How does it handle redirects?

The same way the `jspm-cli` handles it. By checking the github url right ? (see https://github.com/jspm/registry/issues/119#issuecomment-70669662)

> I'm not sure what value it's providing?

It's just a __spell check__ you know...

<br>

@guybedford It would be helpful if you can list what you think is relevant to test here.

**Comment by guybedford** [comment]
@douglasduteil I really really appreciate your efforts to help with testing - the testing on jspm can do with lots of improvements and is really important for project stability.

Here are some related ideas to this work:

* Set this up as a script that we run as a cron to remove dead entries from the registry. Potentially also add the ability to check if overrides have been committed to the original repo to have them removed in the registry when the main repo takes over responsibility for jspm configuration.
* Have all overrides committed along with end-to-end tests that ensure they work, like the tests at https://github.com/jspm/jspm-cli/blob/master/testlibs/tests/bootstrap.js which test libraries directly. We can potentially move the tests there in jspm/jspm-cli/testlibs into this repo, or another special test repo.
* Even more generally than this registry grow a test suite of checking a large database of projects with jspm to see if they work.
* Create an endpoint API test-suite to ensure that an endpoint implements the API correctly and to check it's basic operation.

Those are areas that would all be an amazing help, let me know if anything sounds related to what you're looking to do here.

I also realise there aren't proper contribution guidelines on the project - I've created an issue to improve this at https://github.com/jspm/jspm-cli/issues/461.

**Comment by guybedford** [comment]
From #187 - validation of the JSON files would be a big safety net. That's the only automated check this repo needs I think.

**Comment by guybedford** [comment]
@douglasduteil thanks for kicking this off. Closing as we've merged https://github.com/jspm/registry/pull/290.

**Pull request closed without merging**
