### PR TITLE
Add headroom.js registry and override

### PR DESCRIPTION
**Pull request by smajl**

### CODE REVIEW

**Comment by guybedford** [comment]
Note this should use a `.json` extension.

Also we no longer use `directories` properties in overrides for backwards-compatibility.

**Comment by smajl** [comment]
I fixed the extension and added global export to be safe.

But, what about `directories`? Should I use something like:
```json
"main": "dist/headroom",
"files": ["dist/**/*"]
```
or what? I don't get it. Can't find anything new in docs about that.

**Comment by guybedford** [comment]
@smajl yes exactly we can leave out directories and set the main to `dist/headroom`.

**Comment by smajl** [comment]
I guess it should be OK now.

**Pull request merged**
