### PR TITLE
Changed Source of Foundation

### PR DESCRIPTION
**Pull request by alfkonee**
zurb Foundation Source changed from bower to latest npm feed

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks, does the npm version install and work correctly?

**Comment by alfkonee** [comment]
Yes I've tested it with jspm install npm:foundation-sites and it works perfectly

**Comment by guybedford** [comment]
There's a lot of stuff going on in https://github.com/jspm/registry/blob/master/package-overrides/github/zurb/bower-foundation%405.5.1.json, which I don't think would be captured?

**Comment by alfkonee** [comment]
@guybedford Those overrides won't be captured but npm already resolves all of the dependencies and I updated the for npm:foundation-sites@5.5.1 without the ignores since they weren't needed

**Comment by guybedford** [comment]
:+1: looks good.

**Pull request merged**
