### PR TITLE
Added aurelia-knockout

### PR DESCRIPTION
**Pull request by code-chris**
Added new aurelia-knockout plugin.

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks for your patience... do you think you could ensure this is in the correct alphabetical position?

**Comment by code-chris** [comment]
Yes, of course. I fixed the order of all aurelia packages.

**Comment by guybedford** [comment]
Thanks, it looks like it just needs a rebase to merge now.

**Comment by code-chris** [comment]
done

**Comment by guybedford** [comment]
Thank you!

**Pull request merged**
