### PR TITLE
add @angular overrides

### PR DESCRIPTION
**Pull request by te-je**
For the angular 2 rc.

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks for your patience here. This looks good to merge to me for the Angular 2 override support. I'm wondering if it is worth referencing the ES module sources here with `main: 'esm/index.js'` overrides? That would give us Rollup support for builds.

//cc @robwormald @jeffwhelpley @amcdnl

**Comment by te-je** [comment]
I was getting an error ``Uncaught Module 1 not present`` when using ``main: 'esm/index.js'`` with static builds.

**Comment by guybedford** [comment]
Sure, thanks, I just wanted to check the reasoning.

**Comment by guybedford** [comment]
(deps are not supported for ES modules which may explain that!)

**Pull request merged**
