### PR TITLE
Added hyperagent

### PR DESCRIPTION
**Pull request by Munter**
There is still an outstanding question in #483 on how to get an override to leak a global from a dependency.

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks! Do you mean supporting the `globals` meta as part of the override here? That will be in 0.17, but 0.17 is a really hard release. Working on it!

**Comment by guybedford** [comment]
Perhaps we could support globals in the mean time within the existing configuration system as `shim.globals` in the package config (statically writing into `"globals.jQuery jquery"` etc. It should actually be fairly trivial to implement - if you're interested in a PR along these lines, would be happy to point to the lines of code to implement it.

**Comment by Munter** [comment]
Yeah, that sounds like a good addition. I'll be happy to take a look with some guidance

**Comment by guybedford** [comment]
Awesome. The shim meta-injection is handled in https://github.com/jspm/jspm-cli/blob/master/lib/build.js#L421. It should be straightforward to add a `globals.jQuery: 'jquery'` meta to this shim object, which would then work with SystemJS 0.18.

**Pull request merged**
