### PR TITLE
Add mq4-hover-hover-shim to registry

### PR DESCRIPTION
**Pull request by cvrebert**
See https://github.com/cvrebert/mq4-hover-hover-shim and https://www.npmjs.com/package/mq4-hover-hover-shim

### CODE REVIEW

**Comment by guybedford** [comment]
Nice, is this the best published version for working in both the browser and server?

**Comment by cvrebert** [comment]
The server-side portion and the browser-side portion do different things. [I've set the jspm configuration](https://github.com/cvrebert/mq4-hover-hover-shim/blob/2ee4471b3df5e924109d22461b8c67432322116d/package.json#L60) to load the CommonJS version of the client-side portion.
I consider npm to be the canonical registry for the module.

**Comment by guybedford** [comment]
Nice! Ok that seems great, then we can add the server entry point when conditional environment loading is in too.

**Comment by cvrebert** [comment]
I thought jspm was only for client-side packages?

**Comment by guybedford** [comment]
Yes that is the current focus, but users have requested server support so we have limited support at the moment.

**Pull request merged**
