### PR TITLE
Registry tests jspm/registry#259 + fix golden-layout@1.0.6.json

### PR DESCRIPTION
**Pull request by 2fd**
command tool from file validation: `node test`

`node test --help`
image

`node test -e` display only errors if they occurred
image

image

`node test <package ...>` validate only `registry.json` and overrides from specific package
`node test ace angular react`
image

by default validates all
Example fail: https://travis-ci.org/2fd/registry/builds/54988938
Example passing: https://travis-ci.org/2fd/registry/builds/54989331

### CODE REVIEW

**Comment by 2fd** [comment]
* [x] Registry.json is valid JSON

* [x] registry.json has all names mapping to valid endpoints

> to validate the name of package uses the package Format property of "jspm/ npm" and "jspm/github"

* [x] all package overrides are valid JSON

> uses glob for find all override files of package

**Comment by guybedford** [comment]
This looks amazing! Thank you so much for taking this on!!

I will aim to review this tomorrow for merging here, just need to finish the jspm release cycle first.

**Comment by guybedford** [comment]
Ok, I'm merging this now because we need it! Then will continue to refine the code as we go.

**Comment by guybedford** [comment]
Let me know if you're able to do further review work on this at all, otherwise will hack on it too when I have some time.

Thanks again so much for contributing!

**Comment by 2fd** [comment]
I would with pleasure.

Let me know anything else.

**Comment by guybedford** [comment]
Ok, sure that would be amazing, just look at whatever you feel like - no pressure at all. The initial points would be just:

* Code style - the standard style we have is at https://github.com/jspm/jspm-cli/blob/master/.jshintrc, it would be nice to use this.
* OverrideFile - we seem to loop these from the registry. It is possible for something to be in the registry.json but not have an override and vice-versa. So it may be worth calling this "RegistryEntry" instead and making sure that sources are taken from both the registry.json and the directory listing. Alternatively we can treat the testing of the registry.json validation and testing of the override files as completely separate steps and remove the coupling between the two.

Let me know if that makes sense.

**Comment by 2fd** [comment]
yes! this make sense.

I now work in this

**Pull request merged**
