### PR TITLE
New config for select2

### PR DESCRIPTION
**Pull request by smajl**
- select2 has now new official github repo select2/select2 (old ivaynberg/select2 is redirected to this)
- previous override did not have dependencies set

Is it OK to modify registry entry like this? If not, let me know.

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks. In order not to break the older versions of select2 we should only make the new override apply for the latest version, or at least the version since select2 stopped working. Then we should also copy the old package override to the new name as well.

**Comment by smajl** [comment]
I can copy old override there, but even without it, it should not break anything I guess. I just added missing deps for jquery and css, therefore "repaired it". :) It's almost the same - new override only check, if you have jquery and css and jspm downloads them accordingly.

**Comment by smajl** [comment]
@guybedford Copied old override. Let me know if I should make any other changes.

**Comment by smajl** [comment]
@guybedford I copied the old override. Also, I've realized that it might come in handy to include locale files. I have used them before and they were not included in the previous override.

Hope it's OK now. Let me know, if anything else has to be changed.

**Comment by guybedford** [comment]
Thanks, I've merged manually.

**Pull request merged**
