### PR TITLE
Create d3@4.11.0.json

### LINKED ISSUE #1062: Latest d3 breaks jspm install
The latest d3 (4.11.0) breaks jspm install at runtime with "Error: (SystemJS) Node child_process module not supported in browsers."

This is caused by d3 package.json main: "build/d3.node.js"

Workaround 
add jspm override with: jspm -o d3 "{main: 'build/d3.js'}"

See https://github.com/d3/d3-request/issues/24
https://github.com/gatsbyjs/gatsby/issues/2107#issuecomment-330076798

### PR DESCRIPTION
**Pull request by davismj**
closes #1062

### CODE REVIEW

**Comment by davismj** [comment]
Adapted from https://github.com/rockResolve/registry/pull/1

**Comment by guybedford** [comment]
Better late than never I guess, did you still want this merged? :)

**Comment by davismj** [comment]
I don't see any reason not to.

**Comment by guybedford** [comment]
:+1:

**Pull request merged**
