### PR TITLE
Added big.js, bignumber.js, and JSFromHell

### PR DESCRIPTION
**Pull request by trusktr**
Tested.

### CODE REVIEW

**Comment by trusktr** [comment]
@guybedford Says merged, but I don't seem to see it in master.

**Comment by guybedford** [comment]
Interesting - I'm not sure what happened here? Feel free to send the PR again.

**Comment by crisptrutski** [comment]
Possibly something to do with `Files changed 0`, maybe truskt:master had been reset prior to merge?

**Comment by trusktr** [comment]
Weird haha. Merged thin air.

**Comment by trusktr** [comment]
So weird. New PR: https://github.com/jspm/registry/pull/100

**Pull request merged**
