### PR TITLE
add @reactivex/rxjs

### PR DESCRIPTION
**Pull request by robwormald**
adds @reactivex/rxjs to registry.

### CODE REVIEW

**Comment by robwormald** [comment]
@guybedford not sure how this is going to go with the namespacing - also, can't add an override for it due to the @in the name.

**Comment by guybedford** [comment]
@robwormald `@` in the name is fine, but are you sure you don't want to call it `rxjs`?

**Comment by robwormald** [comment]
`@reactivex/rxjs` is how its published on NPM, and how we refer to it inside NG2, so i think so, yes.

**Comment by robwormald** [comment]
ah, the problem with the override is the slash in the name (silly...). suggestions?

**Comment by guybedford** [comment]
@robwormald unfortunately yes I remember now `/` in the name can't actually be allowed for the jspm registry itself. Is this to make sure that angular2 install finds it? If so one can add `npm:@reactivex/rxjs` as the dependency in the package.json to reference the npm version directly. Also I saw that other override fix you tweeted, should we check that in as an override for `npm:@reactivex/rxjs`?

**Comment by robwormald** [comment]
scratch this, we're bringing rx in core in the next bump. so never mind.

**Pull request closed without merging**
