### PR TITLE
Update famo.us override.

### PR DESCRIPTION
**Pull request by trusktr**
This is theoretically what should work (i think?), but the shim doesn't add

```
"deps src/core/famous.css!";
"deps famous-polyfills";
```

to any files. Why is that again?

### CODE REVIEW

**Comment by guybedford** [comment]
I think we came across this issue before - the shim wildcard doesn't work as a glob.

**Comment by trusktr** [comment]
@guybedford https://www.npmjs.com/package/glob

**Comment by guybedford** [comment]
@trusktr that is, for now, you need to directly shim the paths you are referring to - `"shim": { "some/path/*": ... }` will only catch the files in the specific folder at `some/path/...` and not deeper `some/path/.../...`.

**Comment by trusktr** [comment]
Cool, let me try it and update the PR...

**Comment by trusktr** [comment]
After trying what you suggested (see the new commit) then after installing famous none of the files contain `"deps src/core/famous.css!";` or `"deps famous-polyfills";`.

**Comment by trusktr** [comment]
I can indeed verify that if I use a direct file name (without `.js`) then it works for that one file.

```
"deps src/core/famous.css!";
"deps famous-polyfills";
```

**Comment by speigg** [comment]
Is there an explanation anywhere as to why the modules need to be modified at all? It seems like the override meta-data is duplicated. Why can't the override just be used directly by jspm when determining how to load a module?

**Comment by trusktr** [comment]
@speigg It does work, but not with a `*` wildcard, not even a single wildcard at the end of a path. Direct paths to files work though. @guybedford Am I doing it wrong, or is this a bug?

**Comment by guybedford** [comment]
@speigg good question. There's three options in terms of managing configuration of packages:

1. Inject all the package configuration into the global `config.js` file when you install a package. This will clutter the `config.js` file making it large, but we have a single source of truth for everything.
2. Have a `config.js` per-package that is loaded by SystemJS before loading the package itself. This way we keep the global `config.js` specific to its own needs, and have uncluttered fine-grained package config.
3. Inline config in the modules it applies to. The benefit of this approach is that config is no longer separate from packages - it is tied into their sources and doesn't clutter other areas or need a special request to load.

Currently we're using (3) although I'm still weighing up the merits of switching to (1) or (2).

**Comment by speigg** [comment]
I think this is an important conversation to have (if it isn't being discussed anywhere already). Here is another option:

- Have a `config.js` for the main project configuration, and a `packages.config.js` For everything else (this way at least `config.js` is not cluttered). 

Also, another advantage of not doing (3), i.e, not modifying the original source files: doesn't that make it possible to symlink directly a linked package as part of the development workflow?

**Comment by guybedford** [comment]
@speigg this is an important topic, I have left the architecture open to either method and the final decision point won't be for a few months yet, but it's important to work it out fully.

I like the suggestion, you're right about linking, although there are other operations like directories.lib and npm package builds which still need to be considered. Strangely linking is the one big argument for the single manifest. Note the CDN use case is something that pushes for in-file meta. Allways allowing either option is also an option though, and the loader supports this naturally as config can be a file or in-file.

**Comment by trusktr** [comment]
@guybedford Sweet, so now these shims in package.json work:

```js
  "format":"amd",
  "jspm": {
    "registry":"jspm",
    "directories": {
      "lib": "src"
    },
    "dependencies": {
      "css": "^0.1.0",
      "famous-polyfills": "npm:famous-polyfills"
    },
    "shim": {
      "core/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "events/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "inputs/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "math/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "modifiers/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "physics/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "surfaces/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "transitions/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "utilities/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "views/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      },
      "widgets/*": {
        "deps": ["src/core/famous.css!", "famous-polyfills"]
      }
    }
```

So the files all have 

```js
"format global";
"deps src/core/famous.css!";
"deps famous-polyfills";
```

although but I was expecting to see `"format amd";`.

**Comment by trusktr** [comment]
Of course `"deps": ["src/core/famous.css!"]` is wrong because `directories.lib` is already set to `src`.

**Pull request closed without merging**
