### PR TITLE
waypoints override

### PR DESCRIPTION
**Pull request by selfagency**
adds an override which points to the minified non-jquery version of [waypoints](https://github.com/imakewebthings/waypoints)

### CODE REVIEW

**Comment by aluanhaddad** [comment]
Normally I would say that the package itself should be fixed but there's already a PR to do so that's been open for almost a year https://github.com/imakewebthings/waypoints/pull/533

**Comment by selfagency** [comment]
pushed changes. looks like the author hasn't pushed anything to github in general since february.

**Comment by aluanhaddad** [comment]
Sorry, I botched that request.

**Comment by selfagency** [comment]
ah my bad

**Comment by aluanhaddad** [comment]
@selfagency nope, it was my mistake, I need to get more sleep 😀

**Comment by aluanhaddad** [comment]
@selfagency Thank you!

**Pull request merged**
