### PR TITLE
`three.js` should be `three`

### PR DESCRIPTION
**Pull request by speigg**

### CODE REVIEW

**Comment by speigg** [comment]
Should `three.js` be deleted as well?

**Comment by guybedford** [comment]
Thanks, I'm happy to include both for now. Unfortunately we can't really change registry names once added unless we modify jspm not to save names in the package.json like:

```json
{
  "dependencies": {
    "three.js": "r70"
  }
}
```

And rather store the full canonical name:

```json
{
  "dependencies": {
    "three.js": "github:mrdoob/three.js@r70"
  }
}
```

It's a minor aesthetic change that would allow the registry to change more regularly. Perhaps it's worthwhile.

**Comment by speigg** [comment]
I think it would be worthwhile. It seems less mysterious that way.

**Comment by guybedford** [comment]
Yeah I tend to agree. I've posted an issue at https://github.com/jspm/jspm-cli/issues/526.

**Pull request closed without merging**
