### PR TITLE
Add ngmap

### PR DESCRIPTION
**Pull request by whitneyit**
https://github.com/allenhwkim/angularjs-google-maps

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks! We're actually using the GitHub versions of Angular libraries for Angular1 in jspm currently. Could we use that version here?

**Comment by whitneyit** [comment]
Bump. This was updated a while ago :smile:

**Comment by guybedford** [comment]
Commit updates don't send notifications, so send me a bump sooner next time!

**Comment by whitneyit** [comment]
My fault. I just noticed as well. Cheers for the mere

**Pull request merged**
