### PR TITLE
Add npm:bootstrap@4.0.0-alpha.2 override

### PR DESCRIPTION
**Pull request by frederikschubert**
My stab at [this](https://github.com/jspm/jspm-cli/issues/1892#issuecomment-225148153). I am not sure whether the shim part is correct because I haven't looked into that yet.

### CODE REVIEW

**Comment by jakeNiemiec** [comment]
+1 @frederikschubert add a [files array](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#files) to match the `npm install` behavior.

```json
"files": [
    "dist",
    "grunt",
    "js/*.js",
    "scss/**/*.scss",
    "Gruntfile.js",
    "LICENSE"
  ],
```
// cc @davidstrada

**Comment by guybedford** [comment]
Ok, I'm trusting you both here :)

**Comment by guybedford** [comment]
And thanks so much for pushing this forward.

**Comment by guybedford** [comment]
An update to alter the `bootstrap` entry in the registry to `npm:bootstrap` is welcome.

**Comment by guybedford** [comment]
Oh one more thing we missed out.... because this is on npm, it needs `jspmNodeConversion: false`.

**Pull request merged**
