### PR TITLE
Create language-tags@1.0.3.json

### PR DESCRIPTION
**Pull request by teohhanhui**

### CODE REVIEW

**Comment by guybedford** [comment]
:+1:

**Comment by teohhanhui** [comment]
@guybedford All these should more properly be written as `.json!systemjs-json`, am I right? How do I specify the plugin `systemjs-json` to be installed?

```json
"dependencies": {
  "systemjs-json": "github:systemjs/plugin-json"
}
```
Like this?

**Comment by teohhanhui** [comment]
Or is the `.json!` style preferred in this registry?

**Comment by guybedford** [comment]
@teohhanhui the correct way to do this would be via overriding the npm dependencies in the npm format:

```json
{
  "dependencies": {
    "language-subtag-registry": "~0.3.2",
    "json": "systemjs/plugin-json#0.1"
  }
}
```

**Pull request merged**
