### PR TITLE
superagent@1.0.0

### PR DESCRIPTION
**Pull request by danharper**
Pretty sure I've got this right.

This works locally when running:

```
jspm install superagent=github:visionmedia/superagent@^1.0.0 -o x.json
```

I'm guessing this fixes this issue [**#203 - Importing Superagent fails**](https://github.com/jspm/registry/issues/203)?

---

Edit: I originally had a `dependencies` key in the object as the browser version of superagent only needs 2 dependencies, instead of all the ones in the node version. But apparently you can't override those.

### CODE REVIEW

**Comment by guybedford** [comment]
Nice, thanks!

This seems to work.

Do you have any idea why `npm:superagent` hasn't been published at 1.0.0 yet? You'd think this would be published there as well.

**Comment by danharper** [comment]
I'm not sure. It was only published 9 hours ago. Shall I hold off until they've tagged it on npm and switch to that instead of github?

**Comment by guybedford** [comment]
Yeah that might be a good idea - makes more sense to use the npm published version when they do this.

**Comment by danharper** [comment]
Cool, I'll keep an eye on it and ping you once it's tagged.

**Comment by danharper** [comment]
Looks like the guy who's done the release just doesn't have npm access https://twitter.com/defunctzombie/status/574780655109734401, so won't be long.

**Comment by danharper** [comment]
@guybedford superagent 1.0 is [on NPM now](https://www.npmjs.com/package/superagent), so I've updated this to point there instead of GitHub.

**Comment by guybedford** [comment]
Thanks!

**Pull request merged**
