### PR TITLE
Shim for ismyrnow/Leaflet.groupedlayercontrol

### PR DESCRIPTION
**Pull request by neothemachine**

### CODE REVIEW

**Comment by guybedford** [comment]
Nice!

**Comment by neothemachine** [comment]
Hm, maybe I did something wrong, but it doesn't seem to work yet. When I do `System.import("github:ismyrnow/Leaflet.groupedlayercontrol")` it should load the leaflet dependency I put in the shim as well, right? But it doesn't. Just tested in jspm.io console.

**Comment by guybedford** [comment]
The CDN override cache only gets updated periodically - try it again now?

**Comment by neothemachine** [comment]
Works, great! :)

Maybe you should change the README of the registry repo since it says 
"If the configuration is correct, this will be accepted and that will 
instantly enable the functionality on the endpoint."

**Pull request merged**
