### PR TITLE
Added bootstrap-wizard library and added package override for master branch

### PR DESCRIPTION
**Pull request by SAAirey**

### CODE REVIEW

**Comment by guybedford** [comment]
Perhaps set `directories.lib` to dist here? Also we try to stick to the convention of using unminified sources by default.

**Comment by SAAirey** [comment]
How's that?

**Comment by guybedford** [comment]
Note when you set the `lib`, the paths all change to no longer need the `dist` part. Can you squash?

**Comment by SAAirey** [comment]
Will squash when I've figured out how, give me 5.

**Comment by SAAirey** [comment]
Is that any better? Can't figure out how to squash without it wanting a merge.

**Comment by guybedford** [comment]
Sure, note for future it's `git rebase -i HEAD~5` and then you have to edit the text file to write the letter "s" next to all the commits except the last.

**Comment by SAAirey** [comment]
I did that and it was rebasing locally but wanted a pull. Should have just push -f but completely messed it up. I closed because I seriously messed the history up. Creating a new pull request that is clean unless you say otherwise.

**Comment by guybedford** [comment]
Sure!

**Comment by SAAirey** [comment]
https://github.com/jspm/registry/pull/271

**Pull request closed without merging**
