### PR TITLE
change lodash to github version

### PR DESCRIPTION
**Pull request by Aaike**
The npm version does not work properly in the browser,

### CODE REVIEW

**Comment by Aaike** [comment]
uh , not sure why travis is failing on this , can't see anything wrong

**Comment by guybedford** [comment]
Specifically what issues is the npm version giving?

**Comment by Aaike** [comment]
hmm i installed it earlier and i got an error that it couldn't find browser.js in the process package.
it gets installed like this:
```
"lodash": "npm:lodash@3.6.0",
"npm:lodash@3.6.0": {
    "process": "github:jspm/nodelibs-process@0.1.1"
}
```

So i installed the github version which seems to work and it didn't add the process nodelib.

anyway i just removed the github version and installed the node version , now it actually works without errors...
but i'm still curious about the nodelib process ? why would it pull that in for the browser ?

**Comment by guybedford** [comment]
Lodash accesses the `process` global, so the browserify rule is to include the process shim to enable that.

**Pull request closed without merging**
