### PR TITLE
i18next registry and @1.7.7 override

### PR DESCRIPTION
**Pull request by jerrytk**
http://i18next.com/

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks, does this GitHub repo make the most sense to include then? What about the version on npm?

**Comment by jerrytk** [comment]
I am pretty new at this stuff and so far I haven't been able to come up with working override for npm version :)
In my (maybe naive) opinion npm version pulls in a lot of other dependencies because of some added server-side i18next functionality which might not be all that useful in browser and would just add some overhead. It is basically a different repo: https://github.com/i18next/i18next-node

**Comment by guybedford** [comment]
@jerrytk have you tried `jspm install npm:i18next-client`?

**Comment by jerrytk** [comment]
Thank you for pointing that out! I have completely overlooked that package :( Client version works fine, I'll send new PR.

**Pull request closed without merging**
