### PR TITLE
add vuejs registry.

### PR DESCRIPTION
**Pull request by wprater**
- the cjs modules are not linking correctly when being loaded with require(‘util’)
  where util/index.js exist, it’s trying to load util.js

### CODE REVIEW

**Comment by guybedford** [comment]
Have you tried installing from npm - `npm:vue`?

**Comment by wprater** [comment]
no, will give that a shot now. you think it'll fix the `require` issue as
well?

**Comment by guybedford** [comment]
Yes the `npm` endpoint deals with the compatibility of the Node-style assumptions.

**Comment by wprater** [comment]
ahh! can you point me to the code that deals with this? would love to
learn. will report back in a fee

**Comment by guybedford** [comment]
It's not pretty, but it's at https://github.com/jspm/npm/blob/master/npm.js#L314 and https://github.com/jspm/npm/blob/master/npm.js#L414.

**Comment by wprater** [comment]
installing from npm fixed it!

**Comment by wprater** [comment]
is the general rule of thumb to load from npm if I know the package will be
using cjs module format?

**Comment by guybedford** [comment]
Yes exactly - publish to npm for things npm supports. Publish to github for pure ES6 or use of jspm dependencies / plugins.

**Comment by wprater** [comment]
I should setup a registry for `vue` to map to `npm:vue` then?  or is it
expected for users to know to try NPM for software using CJS?

**Comment by guybedford** [comment]
Adding `vue: npm:vue` into the jspm registry is welcome.

**Pull request closed without merging**
