### PR TITLE
Update famous@0.3.5.json

### PR DESCRIPTION
**Pull request by MajorBreakfast**
@djindjic I need direct access to the `src/` folder's files. I'm only including the physics engine and I'd like to use `jspm bundle` to only pack the modules I really need.

### CODE REVIEW

**Comment by guybedford** [comment]
This is roughly backwards-compatible so can work actually. Note that the `"format": "global"` in the shim isn't necessary as shims are assumed global by default.

**Comment by djindjic** [comment]
we could merge this with shim.format, it looks more declarative.
will this solve @trusktr's issue in https://github.com/jspm/registry/pull/222?

**Comment by MajorBreakfast** [comment]
@djindjic No I think I take it out. After I think about it that makes totally sense: Why would one declare a shim if it was not a global module. After all, global modules are the only type of module that don't explicitly declare what the exports are.

**Comment by MajorBreakfast** [comment]
@guybedford Is `"directories": { "rlib": "." }` necessary? I think it is because as far as I can remember it defaults to `dist/` if that is found. Ready to merge if yes, otherwise I'd like to remove it.

**Comment by guybedford** [comment]
No, the directories.lib isn't necessary as there isn't already one in the Famous repo.

**Comment by MajorBreakfast** [comment]
@guybedford I thought that jspm detects the `dist/` directory and uses that if present as root. So, that's not that case?
I removed it.

**Comment by guybedford** [comment]
No it's not automatic - only if explicitly specified in directories in the package.json. Great thanks, merging.

**Comment by guybedford** [comment]
Actually - the shim needs to be changed to `dist/famous-global` first I think?

**Comment by MajorBreakfast** [comment]
@guybedford Oh yes :) Done

**Comment by djindjic** [comment]
There is an error:
>warn No main entry point detected for github:Famous/famous@0.3.5.
     Try adding an override, or set the package.json "main": false if this is the intention.

(tried to fix it but I couldnt)

**Comment by guybedford** [comment]
@djindjic thanks this was actually a bug in the GitHub endpoint - I've added a fix in 0.10.8.

**Comment by MajorBreakfast** [comment]
@guybedford @djindjic Thanks for resolving this issue! (under a day :P)

**Comment by djindjic** [comment]
@guybedford is it reference in jspm-cli and will be done after jspm-cli release publish?

**Pull request merged**
