### PR TITLE
Added malihu-custom-scrollbar-plugin

### PR DESCRIPTION
**Pull request by Aaike**
tested and working

### CODE REVIEW

**Comment by guybedford** [comment]
Note we're no longer encouraging setting `files`, `ignore` or `directories` for overrides.

**Comment by Aaike** [comment]
@guybedford what would be the alternative then to specify which files should be installed ?

**Comment by Aaike** [comment]
hmm i added the "format": "global" option to the override.
any idea why it would have cjs [here](https://github.jspm.io/malihu/malihu-custom-scrollbar-plugin@3.0.8/jquery.mCustomScrollbar.js) ?

**Comment by guybedford** [comment]
@Aaike the override hadn't refreshed on the CDN yet. Try it again now?

**Pull request merged**
