### PR TITLE
Added overrides and endpoint for three.js

### PR DESCRIPTION
**Pull request by BuildingJarl**
Example of how to use:

import THREE from 'three.js';
import 'three.js/examples/js/renderers/Projector';

### CODE REVIEW

**Comment by guybedford** [comment]
Awesome, thank you.

Do you think you could send a PR to Three itself with this in the package.json? Happy to +1 such a thing if necessary.

**Comment by BuildingJarl** [comment]
Sure no problem. just noticed a small mistake, but before I update I have a question: I added some ignores to the override. Should these be removed? As some people might need them.

**Comment by guybedford** [comment]
Note that ignore can be a folder like `example` if you wanted to reduce this.

If it may be useful, yes you can remove them, but things like docs and examples etc don't need to be in the jspm version of the package.

**Comment by BuildingJarl** [comment]
ok cool. #178 includes a small fix for the endpoint. Sorry to bother you but why again should this also be added to the three.js package.json? [Configuring-Packages-for-jspm](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm) states that It can be added or left out. Since there is already an override, is it needed? Just Curious. Thanks

**Comment by guybedford** [comment]
Because we need to add a new override every time a new version of Three is released. Having the jspm configuration in the package.json of the underlying repo is where it should really be in terms of maintenance and isolation. This package override service should be able to become obsolete eventually.

**Comment by BuildingJarl** [comment]
Oh, I see. Makes sense. Thanks for taking the time to explain this.

**Pull request merged**
